Repository canonic-dev/canonic-samples, pull requests merged in 2021-11, with the labels that each got.

#5 feat(new-sample): flash cards
  Canolo-iOS/Canolo/Base/Card.swift
  Canolo-iOS/Canolo/Modules/Categories/CategoriesViewController.swift
  Canolo-iOS/Canolo/Modules/Players/PlayerListTableCell.swift
  Canolo-iOS/Canolo/Networking/CanonicClient.swift
  Canolo-iOS/Canolo/Supporting Files/Base.lproj/Main.storyboard
  Flashy/Flashy.xcodeproj/project.pbxproj
  Flashy/Flashy.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Flashy/Flashy.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Flashy/Flashy.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Flashy/Flashy/AppDelegate.swift
  Flashy/Flashy/Assets.xcassets/AccentColor.colorset/Contents.json
  Flashy/Flashy/Assets.xcassets/AppIcon.appiconset/Contents.json
  Flashy/Flashy/Assets.xcassets/Contents.json
  Flashy/Flashy/Constants/Constants.swift
  Flashy/Flashy/Extensions/UIColor+Extensions.swift
  Flashy/Flashy/Extensions/UIViewController+Extensions.swift
  Flashy/Flashy/Models/Cards.swift
  Flashy/Flashy/Models/Categories.swift
  Flashy/Flashy/Models/FlashLists.swift
  Flashy/Flashy/Modules/Cards/CardsCollectionViewCell.swift
  Flashy/Flashy/Modules/Cards/CardsViewController.swift
  Flashy/Flashy/Modules/Cards/PagingCollectionViewFlowLayout.swift
  Flashy/Flashy/Modules/Categories/CategoriesViewController.swift
  Flashy/Flashy/Modules/Categories/CategoryTableViewCell.swift
  Flashy/Flashy/Modules/FlashLists/FlashListTableViewCell.swift
  Flashy/Flashy/Modules/FlashLists/FlashListViewController.swift
  Flashy/Flashy/Networking/APIHelper.swift
  Flashy/Flashy/Networking/CanonicClient.swift
  Flashy/Flashy/SceneDelegate.swift
  Flashy/Flashy/Supporting Files/Base.lproj/LaunchScreen.storyboard
  Flashy/Flashy/Supporting Files/Base.lproj/Main.storyboard
  Flashy/Flashy/Supporting Files/Info.plist
Labels: new sample

#12 feat(new-sample): dynamic notifications
  .gitignore
  README.md
  dynamic-website-popups/.gitignore
  dynamic-website-popups/README.md
  dynamic-website-popups/package.json
  dynamic-website-popups/public/favicon.ico
  dynamic-website-popups/public/index.html
  dynamic-website-popups/public/logo192.png
  dynamic-website-popups/public/logo512.png
  dynamic-website-popups/public/manifest.json
  dynamic-website-popups/public/robots.txt
  dynamic-website-popups/screenshots/1.png
  dynamic-website-popups/screenshots/2.png
  dynamic-website-popups/screenshots/3.png
  dynamic-website-popups/src/App.css
  dynamic-website-popups/src/App.js
  dynamic-website-popups/src/index.js
  dynamic-website-popups/yarn.lock
Labels: new sample

#10 feat(new-sample): public roadmap
  README.md
  roadmap/.gitignore
  roadmap/README.md
  roadmap/package.json
  roadmap/public/favicon.ico
  roadmap/public/index.html
  roadmap/public/logo192.png
  roadmap/public/logo512.png
  roadmap/public/manifest.json
  roadmap/public/robots.txt
  roadmap/screenshot.png
  roadmap/src/App.css
  roadmap/src/App.js
  roadmap/src/components/Roadmap/Roadmap.css
  roadmap/src/components/Roadmap/Roadmap.js
  roadmap/src/components/Roadmap/index.js
  roadmap/src/gql/mutations.js
  roadmap/src/gql/queries.js
  roadmap/src/icons/loader.svg
  roadmap/src/icons/upvote.svg
  roadmap/src/index.js
  roadmap/yarn.lock
Labels: enhancement

#22 feat(new-sample):Github PR Dashboard
  README.md
  github-pr-dashboard/README.md
  github-pr-dashboard/package-lock.json
  github-pr-dashboard/package.json
  github-pr-dashboard/public/favicon.ico
  github-pr-dashboard/public/index.html
  github-pr-dashboard/public/logo192.png
  github-pr-dashboard/public/logo512.png
  github-pr-dashboard/public/manifest.json
  github-pr-dashboard/public/robots.txt
  github-pr-dashboard/screenshots/screenshot-1.png
  github-pr-dashboard/screenshots/screenshot-2.png
  github-pr-dashboard/screenshots/screenshot-3.png
  github-pr-dashboard/src/components/Container/Container.js
  github-pr-dashboard/src/components/Container/index.js
  github-pr-dashboard/src/components/Container/style.css
  github-pr-dashboard/src/components/List/List.js
  github-pr-dashboard/src/components/List/index.js
  github-pr-dashboard/src/components/List/style.css
  github-pr-dashboard/src/components/Modal/Modal.js
  github-pr-dashboard/src/components/Modal/index.js
  github-pr-dashboard/src/components/Modal/style.css
  github-pr-dashboard/src/gql/query.js
  github-pr-dashboard/src/index.css
  github-pr-dashboard/src/index.js
  github-pr-dashboard/yarn.lock
Labels: enhancement

#23 fix(ga-responsive): ga and responsive fix
  roadmap/public/index.html
  roadmap/src/components/Roadmap/Roadmap.css
Labels: bug
