Repository canonic-dev/canonic-samples, pull requests merged in 2021-12, with the labels that each got.

#25 fix(ga-query): fixed query duplication and added ga
  release-notes-app/public/index.html
  release-notes-app/src/components/Main.js
  release-notes-app/src/components/Sidebar.js
  release-notes-app/src/components/UI.js
Labels: bug

#26 fix(links): added links for guides
  release-notes-app/README.md
  roadmap/README.md
Labels: bug

#27 fix(notification): added ga and updated readme
  dynamic-website-popups/README.md
  dynamic-website-popups/public/index.html
Labels: bug

#28 fix(title): updated sample title
  roadmap/public/index.html
Labels: bug

#29 fix(ga-link): added ga and live link
  canonic-forms/README.md
  canonic-forms/public/index.html
Labels: bug

#21 feat(new-sample): Postgres Database
  README.md
  postgres-dashboard/.gitignore
  postgres-dashboard/README.md
  postgres-dashboard/package.json
  postgres-dashboard/public/favicon.ico
  postgres-dashboard/public/index.html
  postgres-dashboard/public/logo192.png
  postgres-dashboard/public/logo512.png
  postgres-dashboard/public/manifest.json
  postgres-dashboard/public/robots.txt
  postgres-dashboard/screenshot.png
  postgres-dashboard/src/App.css
  postgres-dashboard/src/App.js
  postgres-dashboard/src/components/DashboardGrid/DashboardGrid.css
  postgres-dashboard/src/components/DashboardGrid/DashboardGrid.js
  postgres-dashboard/src/components/DashboardGrid/index.js
  postgres-dashboard/src/components/DashboardTable/DashboardTable.css
  postgres-dashboard/src/components/DashboardTable/DashboardTable.js
  postgres-dashboard/src/components/DashboardTable/index.js
  postgres-dashboard/src/index.css
  postgres-dashboard/src/index.js
  postgres-dashboard/yarn.lock
Labels: enhancement

#30 fix(readme): updated readme with guide links
  canonic-forms/README.md
  dynamic-website-popups/README.md
  postgres-dashboard/README.md
Labels: bug

#31 feat(new-sample): Customer Information
  README.md
  customer-information/.gitignore
  customer-information/README.md
  customer-information/package.json
  customer-information/public/favicon.ico
  customer-information/public/index.html
  customer-information/public/logo192.png
  customer-information/public/logo512.png
  customer-information/public/manifest.json
  customer-information/public/robots.txt
  customer-information/screenshots/customer-info.png
  customer-information/screenshots/sample.png
  customer-information/src/App.css
  customer-information/src/App.js
  customer-information/src/DummyData.js
  customer-information/src/components/InformationTable/InformationTable.js
  customer-information/src/components/InformationTable/index.js
  customer-information/src/gql/queries.js
  customer-information/src/index.css
  customer-information/src/index.js
  customer-information/src/logo.svg
  customer-information/src/utils/normaliseTableData.js
  customer-information/yarn.lock
Labels: new sample

#34 feat(new-sample): Marketing Dashboard
  README.md
  marketing-dashboard/.gitignore
  marketing-dashboard/README.md
  marketing-dashboard/package.json
  marketing-dashboard/public/favicon.ico
  marketing-dashboard/public/index.html
  marketing-dashboard/public/logo192.png
  marketing-dashboard/public/logo512.png
  marketing-dashboard/public/manifest.json
  marketing-dashboard/public/robots.txt
  marketing-dashboard/screenshots/marketing-dashboard.png
  marketing-dashboard/screenshots/sample.png
  marketing-dashboard/src/App.css
  marketing-dashboard/src/App.js
  marketing-dashboard/src/components/Twitter/Twitter.js
  marketing-dashboard/src/components/Twitter/index.js
  marketing-dashboard/src/components/Youtube/Youtube.js
  marketing-dashboard/src/components/Youtube/index.js
  marketing-dashboard/src/dummyData.js
  marketing-dashboard/src/gql/query.js
  marketing-dashboard/src/index.css
  marketing-dashboard/src/index.js
  marketing-dashboard/src/utils/normaliseData.js
  marketing-dashboard/yarn.lock
Labels: new sample

#35 enh(readme): added links
  customer-information/README.md
  customer-information/public/index.html
  marketing-dashboard/README.md
  marketing-dashboard/public/index.html
Labels: enhancement

#36 feat(new-sample): marketplace-app
  Marketplace-App/README.md
  Marketplace-App/package-lock.json
  Marketplace-App/package.json
  Marketplace-App/public/favicon.ico
  Marketplace-App/public/index.html
  Marketplace-App/public/logo192.png
  Marketplace-App/public/logo512.png
  Marketplace-App/public/manifest.json
  Marketplace-App/public/robots.txt
  Marketplace-App/screenshots/screenshot-1.png
  Marketplace-App/screenshots/screenshot-2.png
  Marketplace-App/screenshots/screenshot-3.png
  Marketplace-App/src/App.js
  Marketplace-App/src/components/header/Header.js
  Marketplace-App/src/components/home/Home.js
  Marketplace-App/src/components/product/Product.js
  Marketplace-App/src/gql/mutation.js
  Marketplace-App/src/gql/query.js
  Marketplace-App/src/index.js
  Marketplace-App/yarn.lock
  README.md
Labels: enhancement

#42 feat(restaurants-app): new sample added
  Flashy/Flashy/Supporting Files/Base.lproj/Main.storyboard
  README.md
  RestaurantApp-iOS/README.md
  RestaurantApp-iOS/Restaurant App.xcodeproj/project.pbxproj
  RestaurantApp-iOS/Restaurant App.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  RestaurantApp-iOS/Restaurant App.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  RestaurantApp-iOS/Restaurant App.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  RestaurantApp-iOS/Restaurant App.xcodeproj/xcshareddata/xcschemes/Restaurant App.xcscheme
  RestaurantApp-iOS/Restaurant App/AppDelegate.swift
  RestaurantApp-iOS/Restaurant App/Constants/Constants.swift
  RestaurantApp-iOS/Restaurant App/Extensions/UIViewController+Extensions.swift
  RestaurantApp-iOS/Restaurant App/Modals/Menu.swift
  RestaurantApp-iOS/Restaurant App/Modals/Order.swift
  RestaurantApp-iOS/Restaurant App/Modals/Restaurant.swift
  RestaurantApp-iOS/Restaurant App/Modules/RestaurantListings/RestaurantListingsViewController.swift
  RestaurantApp-iOS/Restaurant App/Modules/RestaurantListings/RestaurantTableViewCell.swift
  RestaurantApp-iOS/Restaurant App/Modules/RestaurantMenu/RestaurantMenuTableViewCell.swift
  RestaurantApp-iOS/Restaurant App/Modules/RestaurantMenu/RestaurantMenuViewController.swift
  RestaurantApp-iOS/Restaurant App/SceneDelegate.swift
  RestaurantApp-iOS/Restaurant App/Supporting Files/Assets.xcassets/AccentColor.colorset/Contents.json
  RestaurantApp-iOS/Restaurant App/Supporting Files/Assets.xcassets/AppIcon.appiconset/Contents.json
  RestaurantApp-iOS/Restaurant App/Supporting Files/Assets.xcassets/Contents.json
  RestaurantApp-iOS/Restaurant App/Supporting Files/Base.lproj/LaunchScreen.storyboard
  RestaurantApp-iOS/Restaurant App/Supporting Files/Base.lproj/Main.storyboard
  RestaurantApp-iOS/Restaurant App/Supporting Files/Info.plist
  RestaurantApp-iOS/screenshots/one.png
  RestaurantApp-iOS/screenshots/three.png
  RestaurantApp-iOS/screenshots/two.png
Labels: new sample
